library(dplyr)
library(ggplot2)
attach(airquality)
one=airquality%>%filter(Month==9 & Temp>=90)
count(one)
two=airquality%>%arrange(Temp)%>%head(1)
two%>%select(Month,Day)
three=airquality%>%filter(Month==7 |  Month==8)%>%arrange(desc(Temp))%>%head(1)
three%>%select(Month,Day,Temp)
airquality$temp_cesius=(Temp-32)*5/9 
airquality$grade=ifelse(airquality$temp_cesius>=30,"hot","mild")
table(grade)
qplot(grade)
detach(airquality)
